{{- if .Values.OperationsCenter.Enabled -}}
{{- if .Values.rbac.install -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cjoc
  labels:
    app: cjoc
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- if .Values.OperationsCenter.ImagePullSecrets }}
imagePullSecrets:
- name: {{ .Values.OperationsCenter.ImagePullSecrets }}
{{- end -}}
{{- end -}}
{{- end -}}
