{{- if .Values.OperationsCenter.Enabled -}}
{{- if .Values.rbac.install -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccountName }}
  labels:
{{ include "cloudbees-core.labels" . | indent 4 }}
{{- if .Values.OperationsCenter.ImagePullSecrets }}
imagePullSecrets:
- name: {{ .Values.OperationsCenter.ImagePullSecrets }}
{{- end -}}
{{- end -}}
{{- end -}}
