{{- if .Values.Master.Enabled -}}
{{- if .Values.rbac.install -}}
kind: Role
apiVersion: {{ template "rbac.apiVersion" . }}
metadata:
  name: cjoc-agents
  labels:
{{ include "cloudbees-core.labels" . | indent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get","list","watch"]
{{- end -}}
{{- end -}}
