# Install an nginx-ingress controller
 nginx-ingress:
   Enabled: true
   tcp:
     50000: "cloudbees-core/cjoc:50000:PROXY"

 OperationsCenter:
   # Set the HostName for the Operation Center
   HostName: 'core-gke.pcherry.uk'
   Image:
     dockerImage: cloudbees/cloudbees-cloud-core-oc:2.235.2.3
   # Setting ServiceType to ClusterIP creates ingress
   ServiceType: ClusterIP
   Ingress:
     tls:
     ## Set this to true in order to enable TLS on the ingress record
       Enable: true
       Host: core-gke.pcherry.uk
       SecretName: cbci-priv-key-letsencrypt
     Annotations:
       cert-manager.io/cluster-issuer: letsencrypt-core-gke-pcherry-uk

 Master:
   Image:
     dockerImage: cloudbees/cloudbees-core-mm:2.235.2.3
     dockerPullPolicy: Always
     longName: CloudBees Core - Managed Master - 2.235.2.3
   JavaOpts:
     -Dorg.csanchez.jenkins.plugins.kubernetes.pipeline.PodTemplateStepExecution.defaultImage=cloudbees/cloudbees-core-agent:2.249.2.4
     -Dcom.cloudbees.opscenter.client.casc.ConfigurationUpdaterTask.recurrencePeriod=1
