nginx-ingress:
  Enabled: false
  controller:
    service:
      externalTrafficPolicy: Local
OperationsCenter:
  Enabled: true
  Name: cjoc
  Image:
    dockerImage: cloudbees/cloudbees-cloud-core-oc:2.176.4.3
    dockerPullPolicy: Always
    longName: CloudBees Core - 2.176.4.3
  Platform: standard
  Component: jenkins-master
  ContextPath: /cjoc
  HostName: null
  Protocol: http
  Cpu: '1'
  Memory: 1G
  RunAsUser: 1000
  FsGroup: 1000
  ServicePort: 80
  ServiceAgentListenerPort: 50000
  AgentListenerPort: 50000
  ServiceType: ClusterIP
  ServiceAnnotations: {}
  ContainerPort: 8080
  HealthProbes: true
  HealthProbesTimeout: 300
  HealthProbeLivenessFailureThreshold: 12
  CSRF:
    ProxyCompatibility: false
  LoadBalancerSourceRanges:
  - 0.0.0.0/0
  JavaOpts: null
  NodeSelector: []
  Tolerations: []
  Annotations: {}
  Ingress:
    ApiVersion: extensions/v1beta1
    Annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: 'false'
    tls:
      Enable: false
      SecretName: cloudbees-core-example-com-tls
      Host: jenkins.cluster.local
  Route:
    tls:
      Enable: false
  Project:
    name: null
Master:
  Enabled: true
  Image:
    dockerImage: cloudbees/cloudbees-core-mm:2.176.4.3
    dockerPullPolicy: Always
    longName: CloudBees Core - Managed Master - 2.176.4.3
Agents:
  Enabled: true
Persistence:
  Enabled: true
  Annotations: {}
  AccessMode: ReadWriteOnce
  Size: 20Gi
  volumes: null
  mounts: null
rbac:
  install: true
  serviceAccountName: default
  masterManagementRoleName: master-management
  podsManagementRoleName: pods-all
  roleRef: cluster-admin
